import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import {
  Media,
  MediaDetailView,
  type MediaItem,
} from '../../src/components/Chat/InteractiveComponents';

const MediaExample: React.FC = () => {
  const [detailViewVisible, setDetailViewVisible] = useState(false);
  const [selectedMedia, setSelectedMedia] = useState<MediaItem | MediaItem[] | null>(null);

  // Sample image with comprehensive metadata
  const sampleImage: MediaItem = {
    id: 'img-1',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    title: 'Mountain Landscape',
    caption: 'A breathtaking view of snow-capped mountains during golden hour',
    summary: 'Beautiful landscape photography captured in the Swiss Alps during sunset. The interplay of light and shadow creates a dramatic scene.',
    description: 'This stunning photograph showcases the majestic beauty of the Swiss Alps. Taken during the golden hour, the warm sunlight illuminates the snow-covered peaks while casting long shadows across the valleys below.',
    metadata: {
      fileName: 'mountain-landscape.jpg',
      fileSize: 2457600, // ~2.4 MB
      mimeType: 'image/jpeg',
      format: 'jpeg',
      width: 4000,
      height: 2667,
      aspectRatio: 1.5,
      colorSpace: 'sRGB',
      colorDepth: 24,
      hasAlpha: false,
      camera: {
        make: 'Canon',
        model: 'EOS 5D Mark IV',
        lens: 'EF 24-70mm f/2.8L II USM',
        focalLength: 35,
        aperture: 8,
        iso: 100,
        shutterSpeed: '1/125',
        flash: false,
      },
      location: {
        latitude: 46.5197,
        longitude: 7.9539,
        altitude: 3454,
      },
      createdAt: new Date('2024-06-15T18:45:00Z'),
      modifiedAt: new Date('2024-06-15T19:30:00Z'),
    },
    tags: ['landscape', 'mountains', 'nature', 'photography', 'switzerland', 'golden-hour'],
    author: 'Sarah Mitchell',
    source: 'Unsplash',
    license: 'Unsplash License',
    alt: 'Panoramic view of snow-covered mountain peaks at sunset',
  };

  // Sample GIF
  const sampleGif: MediaItem = {
    id: 'gif-1',
    type: 'gif',
    url: 'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
    thumbnailUrl: 'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/200.gif',
    title: 'Animated Loading Spinner',
    caption: 'Smooth loading animation with modern design',
    isAnimated: true,
    autoPlay: true,
    loop: true,
    metadata: {
      fileName: 'loading-spinner.gif',
      fileSize: 524288, // 512 KB
      mimeType: 'image/gif',
      format: 'gif',
      width: 480,
      height: 270,
      aspectRatio: 1.78,
      duration: 2.5,
    },
    tags: ['animation', 'loading', 'spinner', 'ui', 'design'],
    author: 'Design Studio',
    source: 'Giphy',
    license: 'Creative Commons',
  };

  // Sample video
  const sampleVideo: MediaItem = {
    id: 'vid-1',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',
    title: 'Big Buck Bunny',
    caption: 'Open source animated short film about a giant rabbit',
    summary: 'Big Buck Bunny is a short computer-animated comedy film featuring a large rabbit and three bullying rodents.',
    description: 'Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself. When one sunny day three rodents rudely harass him, something snaps... and the rabbit aint no bunny anymore! In the typical cartoon tradition he prepares the nasty rodents a comical revenge.',
    metadata: {
      fileName: 'big-buck-bunny.mp4',
      fileSize: 158008374, // ~150 MB
      mimeType: 'video/mp4',
      format: 'mp4',
      width: 1920,
      height: 1080,
      aspectRatio: 1.78,
      duration: 596, // 9:56 minutes
      frameRate: 24,
      bitrate: 2000,
      codec: 'H.264',
      createdAt: new Date('2008-04-10T00:00:00Z'),
    },
    tags: ['animation', 'short-film', 'comedy', 'open-source', 'blender'],
    author: 'Blender Foundation',
    source: 'Blender Open Movie Project',
    license: 'Creative Commons Attribution 3.0',
    isMuted: false,
    autoPlay: false,
    loop: false,
  };

  // Sample audio
  const sampleAudio: MediaItem = {
    id: 'aud-1',
    type: 'audio',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    title: 'SoundHelix Song #1',
    caption: 'Generated music composition showcasing algorithmic creativity',
    summary: 'A unique piece of music generated by SoundHelix, an algorithmic music composition system.',
    description: 'SoundHelix is a framework for generating musical sequences using Java. This particular composition demonstrates the systems ability to create coherent and pleasant melodies through algorithmic composition.',
    metadata: {
      fileName: 'soundhelix-song-1.mp3',
      fileSize: 4718592, // ~4.5 MB
      mimeType: 'audio/mpeg',
      format: 'mp3',
      duration: 294, // 4:54 minutes
      bitrate: 128,
      createdAt: new Date('2023-01-15T10:00:00Z'),
    },
    tags: ['music', 'algorithmic', 'composition', 'generated', 'instrumental'],
    author: 'SoundHelix',
    source: 'SoundHelix.com',
    license: 'Free for personal use',
    isMuted: false,
    autoPlay: false,
    loop: false,
  };

  // Gallery of multiple images
  const sampleGallery: MediaItem[] = [
    {
      id: 'gallery-1',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
      title: 'Mountain Landscape',
      caption: 'Majestic mountain peaks at sunset',
      metadata: { width: 4000, height: 2667, fileSize: 2457600 },
      tags: ['landscape', 'mountains', 'nature'],
    },
    {
      id: 'gallery-2',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
      title: 'Forest Path',
      caption: 'A serene path through autumn forest',
      metadata: { width: 3000, height: 2000, fileSize: 1843200 },
      tags: ['forest', 'nature', 'autumn'],
    },
    {
      id: 'gallery-3',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05',
      title: 'Northern Lights',
      caption: 'Aurora Borealis dancing in the night sky',
      metadata: { width: 3500, height: 2333, fileSize: 2150400 },
      tags: ['aurora', 'night', 'nature', 'sky'],
    },
    {
      id: 'gallery-4',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff',
      title: 'Lake Reflection',
      caption: 'Crystal clear lake reflecting mountain scenery',
      metadata: { width: 4200, height: 2800, fileSize: 2867200 },
      tags: ['lake', 'reflection', 'mountains'],
    },
    {
      id: 'gallery-5',
      type: 'video',
      url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      thumbnailUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg',
      title: 'Elephants Dream',
      caption: 'Open source animated short film',
      metadata: {
        width: 1920,
        height: 1080,
        duration: 654,
        fileSize: 142606336,
      },
      tags: ['animation', 'short-film', 'sci-fi'],
    },
  ];

  const handleMediaPress = (media: MediaItem, index?: number) => {
    console.log('Media pressed:', media.title, 'Index:', index);
  };

  const handleExpandPress = (media: MediaItem | MediaItem[]) => {
    setSelectedMedia(media);
    setDetailViewVisible(true);
  };

  const handleDownload = (media: MediaItem) => {
    console.log('Download media:', media.title);
    // In a real app, implement download functionality
  };

  const handleShare = (media: MediaItem) => {
    console.log('Share media:', media.title);
    // In a real app, implement share functionality
  };

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      {/* Image Demo */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Image - Mini Mode</Text>
        <Text style={styles.sectionDescription}>
          High-resolution landscape photo with comprehensive metadata, camera info, and location data.
          Tap the expand button to view full details.
        </Text>
        <Media
          media={sampleImage}
          mode="mini"
          showCaption={false}
          onExpandPress={() => handleExpandPress(sampleImage)}
          onMediaPress={handleMediaPress}
        />
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Image - Full Mode</Text>
        <Text style={styles.sectionDescription}>
          Full-featured display with caption, metadata, tags, and action buttons.
        </Text>
        <Media
          media={sampleImage}
          mode="full"
          showCaption={true}
          showMetadata={true}
          onMediaPress={handleMediaPress}
          onDownload={handleDownload}
          onShare={handleShare}
        />
      </View>

      {/* GIF Demo */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>GIF - Animated Content</Text>
        <Text style={styles.sectionDescription}>
          Animated GIF with auto-play and loop functionality. Perfect for loading indicators and animations.
        </Text>
        <Media
          media={sampleGif}
          mode="full"
          showCaption={true}
          showMetadata={true}
          maxHeight={300}
          onMediaPress={handleMediaPress}
          onDownload={handleDownload}
          onShare={handleShare}
        />
      </View>

      {/* Video Demo */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Video - Mini Mode</Text>
        <Text style={styles.sectionDescription}>
          Video player with thumbnail, play button, and duration display. Click to play.
        </Text>
        <Media
          media={sampleVideo}
          mode="mini"
          showCaption={false}
          onExpandPress={() => handleExpandPress(sampleVideo)}
          onMediaPress={handleMediaPress}
        />
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Video - Full Mode</Text>
        <Text style={styles.sectionDescription}>
          Complete video information including codec, bitrate, resolution, and licensing.
        </Text>
        <Media
          media={sampleVideo}
          mode="full"
          showCaption={true}
          showMetadata={true}
          onMediaPress={handleMediaPress}
          onDownload={handleDownload}
          onShare={handleShare}
        />
      </View>

      {/* Audio Demo */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Audio Player</Text>
        <Text style={styles.sectionDescription}>
          Audio player with playback controls and track information. Algorithmic music composition.
        </Text>
        <Media
          media={sampleAudio}
          mode="full"
          showCaption={true}
          showMetadata={true}
          maxHeight={300}
          onMediaPress={handleMediaPress}
          onDownload={handleDownload}
          onShare={handleShare}
        />
      </View>

      {/* Gallery Demo */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Gallery - Multiple Media Items</Text>
        <Text style={styles.sectionDescription}>
          Interactive gallery with navigation, thumbnails, and slideshow. Contains {sampleGallery.length} items
          including images and videos.
        </Text>
        <Media
          media={sampleGallery}
          mode="full"
          showCaption={true}
          onMediaPress={handleMediaPress}
          onExpandPress={() => handleExpandPress(sampleGallery)}
          onDownload={handleDownload}
          onShare={handleShare}
          gallery={{
            showThumbnails: true,
            enableSwipe: true,
            showIndicators: true,
            initialIndex: 0,
          }}
        />
      </View>

      {/* Detail View Demo Button */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Full-Screen Detail Views</Text>
        <Text style={styles.sectionDescription}>
          Open any media in a full-screen modal with enhanced viewing experience, zoom capabilities,
          and complete metadata display.
        </Text>

        <TouchableOpacity
          style={styles.detailViewButton}
          onPress={() => handleExpandPress(sampleImage)}
        >
          <Text style={styles.detailViewButtonText}>🖼️ View Image in Detail Mode</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.detailViewButton}
          onPress={() => handleExpandPress(sampleVideo)}
        >
          <Text style={styles.detailViewButtonText}>🎥 View Video in Detail Mode</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.detailViewButton}
          onPress={() => handleExpandPress(sampleAudio)}
        >
          <Text style={styles.detailViewButtonText}>🎵 View Audio in Detail Mode</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.detailViewButton}
          onPress={() => handleExpandPress(sampleGallery)}
        >
          <Text style={styles.detailViewButtonText}>📸 View Gallery in Detail Mode ({sampleGallery.length} items)</Text>
        </TouchableOpacity>
      </View>

      {/* Feature Highlights */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Key Features</Text>
        <View style={styles.featureList}>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Support for Image, GIF, Video, and Audio</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Mini and Full display modes</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Gallery support with navigation and thumbnails</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Comprehensive metadata display</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Camera EXIF data and location info</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Captions, summaries, and descriptions</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Tags, licensing, and attribution</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Download and share functionality</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Responsive sizing and aspect ratio handling</Text>
          </View>
          <View style={styles.featureItem}>
            <Text style={styles.featureIcon}>✓</Text>
            <Text style={styles.featureText}>Full-screen detail view with zoom</Text>
          </View>
        </View>
      </View>

      <View style={styles.bottomPadding} />

      {/* Media Detail View Modal */}
      {selectedMedia && (
        <MediaDetailView
          visible={detailViewVisible}
          media={selectedMedia}
          onClose={() => {
            setDetailViewVisible(false);
            setSelectedMedia(null);
          }}
          onMediaPress={handleMediaPress}
          onDownload={handleDownload}
          onShare={handleShare}
          showMetadata={true}
          enableZoom={true}
        />
      )}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F2F2F7',
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 4,
  },
  sectionDescription: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 12,
    lineHeight: 20,
  },
  bottomPadding: {
    height: 40,
  },
  detailViewButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  detailViewButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  featureList: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  featureIcon: {
    fontSize: 16,
    color: '#10B981',
    marginRight: 12,
    fontWeight: '700',
  },
  featureText: {
    fontSize: 14,
    color: '#374151',
    flex: 1,
  },
});

export default MediaExample;
